---
- hosts: conjurdemo
  vars:
    ansible_ssh_user: "{{ lookup('cyberark.conjur.conjur_variable', 'ssh_keys/username') }}"
    ansible_ssh_private_key_file: "{{ lookup('cyberark.conjur.conjur_variable', 'ssh_keys/sshprvkey', as_file=True) }}"
  become: yes
  handlers:
  - systemd:
      name: httpd
      state: restarted
    listen: restart httpd
  tasks:
  - yum:
      name: httpd
      state: latest
  - firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: enabled
  - systemd:
      name: httpd
      state: restarted
      enabled: yes
  - template:
      src: index.html.j2
      dest: /var/www/html/index.html
    notify: restart httpd
